"""
Utility for displaying matplotlib JavaScript HTML animations responsively in notebooks.

This module provides a simple function to load HTML animation files (generated by
matplotlib's to_jshtml()) and display them at 100% width in Jupyter/Quarto notebooks.
"""

from IPython.display import HTML


def display_html_animation(filename, container_class='animation-container'):
    """
    Display an HTML animation file with responsive 100% width styling.

    Parameters
    ----------
    filename : str
        Path to the HTML file to display
    container_class : str, optional
        CSS class name for the container (default: 'animation-container')

    Returns
    -------
    IPython.display.HTML
        HTML object that can be displayed in notebooks

    Examples
    --------
    >>> from viz_jshtml import display_html_animation
    >>> display_html_animation('my_animation.html')

    >>> # With custom container class
    >>> display_html_animation('pendulum.html', container_class='pendulum-viz')
    """
    with open(filename, 'r') as f:
        html_content = f.read()

    responsive_html = f"""
    <div style="width: 100%; max-width: 100%; overflow: hidden;">
        <style>
            .{container_class} {{
                width: 100% !important;
                max-width: 100% !important;
            }}
            .{container_class} img {{
                width: 100% !important;
                height: auto !important;
            }}
        </style>
        <div class="{container_class}">
            {html_content}
        </div>
    </div>
    """

    return HTML(responsive_html)


# Convenience alias
show = display_html_animation
